exclude: '^(build|docs|.devcontainer|.vscode|scss)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=12000']
      - id: check-json
        exclude: (^.devcontainer/|^.vscode)
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        exclude: (^.gitlab/)
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: (^.gitlab/)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=E501,W503,E712,E203

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: http://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
